services:
  - type: worker
    name: chatroulette-bot
    env: python
    plan: free
    startCommand: "python bot.py"
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: BOT_TOKEN
        sync: false
